name: Build

on:
  push:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get branch name
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Debug
      run: echo ${{ env.BRANCH_NAME }}
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        ref: ${{ env.BRANCH_NAME }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: codecov/codecov-action@v2
    - uses: codacy/codacy-coverage-reporter-action@v1
      with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
    - name: Upload jars
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs
    - name: Upload distributions
      uses: actions/upload-artifact@v3
      with:
        name: distributions
        path: build/distributions
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: build/jpackage/*.deb
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: build/reports
