name: Release (ubuntu-latest)

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ./github/workflows/ubuntu-latest.yml
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/distributions
          build/libs
          build/jpackage/*.deb
