name: Build (ubuntu-latest)

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build jpackage publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: codecov/codecov-action@v2
    - uses: codacy/codacy-coverage-reporter-action@v1
      with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
    - name: Upload jars
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs
    - name: Upload distributions
      uses: actions/upload-artifact@v3
      with:
        name: distributions
        path: build/distributions
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: build/jpackage/*.deb
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: build/reports
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/distributions
          build/libs
          build/jpackage/*.deb
